CREATE TABLE IF NOT EXISTS FRAUD_MODEL_METRICS (
    RUN_ID STRING,
    MODEL_NAME STRING,
    PRECISION FLOAT,
    RECALL FLOAT,
    F1 FLOAT,
    ACCURACY FLOAT,
    LATENCY_P95_MS FLOAT,
    DRIFT_MAX_PSI FLOAT,
    CREATED_AT TIMESTAMP_NTZ
);

